# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lemonade < Formula
  desc "Lemonade is a remote utility tool.
(copy, paste and open browser) over TCP."
  homepage "https://github.com/cnt0/lemonade"
  version "1.1.3-cnt0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Darwin_x86_64.tar.gz"
      sha256 "7a74b1a8effb2df4bca0f192fba3565ebde6a3fa575dd150efb63dff4fdcf58c"

      def install
        bin.install "lemonade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Darwin_arm64.tar.gz"
      sha256 "3b698627a9374f75e1e32622b72063a6c3ec20465cc4afeccac9fabd05181838"

      def install
        bin.install "lemonade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Linux_x86_64.tar.gz"
      sha256 "24ca954643f39f48213a0e18b308c3f2e8df38b763c617db7821ec889347ebcf"

      def install
        bin.install "lemonade"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Linux_arm64.tar.gz"
      sha256 "eb1f7fd38e85ed76d304e6fabce331060864611f82f8201767b0c8118a4586cb"

      def install
        bin.install "lemonade"
      end
    end
  end

  service do
    run [bin/"lemonade", "server"]
    keep_alive true
    log_path var/"log/lemonade.log"
    error_log_path var/"log/lemonade.log"
  end
end
