# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lemonade < Formula
  desc "Lemonade is a remote utility tool.
(copy, paste and open browser) over TCP."
  homepage "https://github.com/cnt0/lemonade"
  version "1.1.3-cnt0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Darwin_x86_64.tar.gz"
      sha256 "87ce59101675afae62fa798c008e231310244deed5c6f5af9a67da1c7275330a"

      def install
        bin.install "lemonade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Darwin_arm64.tar.gz"
      sha256 "78949ad8550d5164ba8248316919689fe7799d6a36998d7b521542a253b1f8bc"

      def install
        bin.install "lemonade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Linux_x86_64.tar.gz"
      sha256 "e79dd94dc99c1dab839f2e50b30d84311257b5e8e690df839fa760d051f7c2fe"

      def install
        bin.install "lemonade"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Linux_arm64.tar.gz"
      sha256 "3a455f3f19c2577b931922ae4f34ca4a56c2a71ec0cb3e283fd6f6fab303fd64"

      def install
        bin.install "lemonade"
      end
    end
  end

  service do
    run [bin/"lemonade", "server"]
    keep_alive true
    log_path var/"log/lemonade.log"
    error_log_path var/"log/lemonade.log"
  end
end
