# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lemonade < Formula
  desc "Lemonade is a remote utility tool.
(copy, paste and open browser) over TCP."
  homepage "https://github.com/cnt0/lemonade"
  version "1.1.3-cnt0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Darwin_arm64.tar.gz"
      sha256 "5abfbf6e9c20b2d9b4b9bb70a242365182453a96421a19f38600636d3cb7b18e"

      def install
        bin.install "lemonade"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Darwin_x86_64.tar.gz"
      sha256 "da7ef8ba61993d2b457b63b8264b860ef7177e80a059ed18656e87c368041da7"

      def install
        bin.install "lemonade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Linux_arm64.tar.gz"
      sha256 "1e2d90492c65d61bda5d2b26202f58504bdab7ed3bcaa304313413bf3ab6093e"

      def install
        bin.install "lemonade"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cnt0/lemonade/releases/download/v1.1.3-cnt0/lemonade_Linux_x86_64.tar.gz"
      sha256 "0daa5de49fa449779b2e9678600de15ec7ece24e5fea9130e044401a5d1fe9cf"

      def install
        bin.install "lemonade"
      end
    end
  end

  service do
    run: [bin/"lemonade", "server"]
  end
end
